### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by smith-m** [caryli/dbgmapreduce#1]
When running this program, I get the error "Your PC ran into a problem that it couldn't handle, and now it needs to restart." 

This code seems to be broken.

**Comment by caryli** [comment]
Hm, I think I might know the issue, how much wood is your PC made of?

**Comment by smith-m** [comment]
It is microsoft windows over 9000. Would that cause any problems?

**Comment by smith-m** [comment]
Hey, can you help?
